name: coachboard
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  freezed_annotation: ^2.2.0
  freezed: ^2.2.0
  build_runner: ^2.3.2
  go_router: ^5.1.1
  intl: ^0.17.0
  font_awesome_flutter: ^10.2.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  